name: scrypto_wallet
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  js: ^0.6.4
  isolated_worker: ^0.1.1
  get: ^4.6.1
  elliptic: ^0.3.8
  openapi_generator_annotations: ^3.3.0
  babylon_pte_api:
    path: ../packages/babylon_pte_api
  babylon_pte_manifest:
    path: ../packages/babylon_pte_manifest 
  babylon_pte_extenstion:
    path: ../packages/babylon_pte_extenstion
  jdenticon_dart: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_neumorphic: ^3.2.0
  velocity_x: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  openapi_generator: ^3.3.0+1
  analyzer: ^3.0.0
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
